roles:
  - name: geerlingguy.mysql
    version: 3.3.2
  - name: geerlingguy.apache
    version: 3.1.4
  - name: mkayontour.icingaweb2
    src: git+https://github.com/mkayontour/ansible-icingaweb2
    version: master
collections:
  - name: git+https://github.com/Icinga/ansible-collection-icinga.git
    version: 70da11c9e7b82ebb439289f560b85f4b4537a47a # PR #52 - Improve compatibility for Ansible 2.9 and Python 3.6

## or manually for Ansible < 2.10
# mkdir -p $HOME/.ansible/collections/ansible_collections/icinga
# cd $HOME/.ansible/collections/ansible_collections/icinga
# git clone https://github.com/Icinga/ansible-collection-icinga.git icinga
# cd icinga
# git checkout -f 70da11c9e7b82ebb439289f560b85f4b4537a47a
