- name: Update /etc/hosts so we won't need any DNS
  hosts: all
  tasks:
    - name: Create a hosts entry for each node
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }} {{ item | regex_replace('\\..*', '') }}"
        regexp: '{{ item }}'
      with_items: "{{ groups['all'] }}"
