- name: MySQL import icingaweb2 schema
  block:
    - name: build mysql command
      set_fact:
        mysqlcmd: >-
          mysql
          {% if icingaweb2_resources.icingaweb_db.host| default('localhost') != 'localhost'  %}
            -h "{{ icingaweb2_resources['icingaweb_db'].host }}" {%- endif %}
          {% if icingaweb2_resources['icingaweb_db'].port is defined %} -P "{{ icingaweb2_resources['icingaweb_db'].port }}" {%- endif %}
          -u "{{ icingaweb2_resources['icingaweb_db'].username |default('icinga2') }}"
          -p"{{ icingaweb2_resources['icingaweb_db'].password }}"
          "{{ icingaweb2_resources['icingaweb_db'].dbname |default('icinga2') }}"

    - name: MySQL check for icingaweb2 schema
      shell: >
        {{ mysqlcmd }}
        -Ns -e "select name from icingaweb_user limit 1"
      failed_when: false
      changed_when: false
      register: db_table

    - name: MySQL import icingaweb2 schema
      shell: >
        {{ mysqlcmd }}
        < /usr/share/doc/icingaweb2/schema/mysql.schema.sql
      when: db_table.rc != 0

    - name: MySQL create default icingaweb2 account
      shell: >
        {{ mysqlcmd }}
        -Ns -e 'INSERT INTO icingaweb_user (name, active, password_hash)
        VALUES ("icingaadmin", 1, "$1$3no6eqZp$FlcHQDdnxGPqKadmfVcCU.")'  # default pw: icinga
      when: db_table.rc != 0

  when: icingaweb2_resources['icingaweb_db'] is defined
